ibmdb: Lock at version ibm_db@2.0
* ibm_db@2.1.0 fixes the clidriver permission issue. See:
  https://github.com/ibmdb/node-ibm_db/pull/284

* ibm_db@2.1.0 throws the following error on `npm run start`:

user@host:~/github/plotly-database-connector$ npm run start

> plotly-database-connector@2.0.2 start /home/user/github/plotly-database-connector
> cross-env NODE_ENV=production electron ./

App threw an error during load
Error: libdb2.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/home/user/github/plotly-database-connector/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/github/plotly-database-connector/node_modules/ibm_db/lib/odbc.js:27:31)
    at Object.<anonymous> (/home/user/github/plotly-database-connector/node_modules/ibm_db/lib/odbc.js:1761:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.e.__esModule.default (/home/user/github/plotly-database-connector/backend/webpack:/external "ibm_db":1:1)
    at t (/home/user/github/plotly-database-connector/backend/webpack:/webpack/bootstrap 1020c4d3a5e21580f839:19:1)
    at Object.<anonymous> (/home/user/github/plotly-database-connector/backend/webpack:/backend/persistent/datastores/ibmdb2.js:1:15)
    at t (/home/user/github/plotly-database-connector/backend/webpack:/webpack/bootstrap 1020c4d3a5e21580f839:19:1)